// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: event.sql

package db

import (
	"context"
	"time"
)

const createEvent = `-- name: CreateEvent :one
INSERT INTO "event" (
    name, date
) VALUES (
    $1, $2
) RETURNING id, name, date, deleted_at, created_at
`

type CreateEventParams struct {
	Name string    `json:"name"`
	Date time.Time `json:"date"`
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRowContext(ctx, createEvent, arg.Name, arg.Date)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Date,
		&i.DeletedAt,
		&i.CreatedAt,
	)
	return i, err
}
