// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import (
	"context"
)

type Querier interface {
	CreateCard(ctx context.Context, arg CreateCardParams) (Card, error)
	CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error)
	CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteUser(ctx context.Context, dollar_1 interface{}) error
	GetCard(ctx context.Context, id int64) (Card, error)
	GetUser(ctx context.Context, username string) (User, error)
	GetUserID(ctx context.Context, username string) (int64, error)
	ListCardsFromUserByUsername(ctx context.Context, username string) ([]ListCardsFromUserByUsernameRow, error)
	ListMostRecentCard(ctx context.Context, arg ListMostRecentCardParams) ([]Card, error)
	ListUser(ctx context.Context, arg ListUserParams) ([]string, error)
	UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error
}

var _ Querier = (*Queries)(nil)
