// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import (
	"context"
)

type Querier interface {
	CreateCard(ctx context.Context, arg CreateCardParams) (Card, error)
	CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error)
	CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteUser(ctx context.Context, dollar_1 interface{}) error
	GetCard(ctx context.Context, id int64) (GetCardRow, error)
	GetUserAuth(ctx context.Context, username string) (User, error)
	GetUserByID(ctx context.Context, id int64) (GetUserByIDRow, error)
	GetUserID(ctx context.Context, username string) (int64, error)
	ListCardsByUserID(ctx context.Context, accused int64) ([]ListCardsByUserIDRow, error)
	ListMostRecentCard(ctx context.Context, arg ListMostRecentCardParams) ([]ListMostRecentCardRow, error)
	ListUser(ctx context.Context, arg ListUserParams) ([]ListUserRow, error)
	ListUserFilter(ctx context.Context, arg ListUserFilterParams) ([]ListUserFilterRow, error)
	UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error
}

var _ Querier = (*Queries)(nil)
